[google_drive]
gene_full = "1mLx-mh1k4M4zNAOATLQiFXy06s0tfZHl"
gene_nlp = "1DiRskqNZ3ph04f3QsyI-RjMxuVPKehaq"
gene_signal = "1-VO0v49BFRIpvJl2ix0WzVnRjP1hxNRh"
semi_full = "1CwfeO6WY7gKqov5mAtaD1ffvsxBzdjR5"
semi_nlp = "1Qq3X1O7hpIV51xcet_TlTinqJ8SniIyN"
semi_signal = "1GSmeQvnoGU75rEI4v8QqITLj7KRrDQOQ"
patents = "1xI60lbOCbY7BQ_Wq9tX-cs6Zzvme8B9L"
cpc = "1L98w0Cx7Dh308W70W080dVabzN_34Kwk"
assignee = "1CBRr7564K7hGdd75ffE8IRIvjesolqkd"
title = "1BfEZRKC7qqWGna9uiqjdxzvhDRke8ZzN"
